"""empty message

Revision ID: a7eb7cd7dd5c
Revises: 
Create Date: 2024-04-16 19:31:11.675904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7eb7cd7dd5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marathon', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('bibnum', sa.Integer(), nullable=False),
    sa.Column('record', sa.String(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
