wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722404072
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      - 23
      - 61
      4: 3.10.13
      5: 0.17.5
      8:
      - 1
      - 5
      13: linux-x86_64
